# Use it with always suggest updating pull request branches
name: Github branches consistency check

on: pull_request

jobs:
  fail-on-merge-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Check for merge commits
        shell: bash
        run: |
          MERGE_COMMITS=$(git log --oneline --merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --)
          if [ -n "$MERGE_COMMITS" ]; then
            echo $MERGE_COMMITS
            exit 1
          fi