name: Manual Release to Maven Central

on:
  workflow_dispatch:

jobs:
  run-on-release:
    runs-on: ubuntu-latest
    if: github.repository == 'ttypic/git-playground'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Read VERSION_NAME from gradle.properties
        id: version
        run: |
          VERSION_NAME=$(grep '^VERSION_NAME' gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Compare version with tag
        run: |
          if [ "$VERSION" != "$TAG" ]; then
            echo "VERSION ($VERSION) does not match tag ($TAG)."
            exit 1
          fi
        env:
          VERSION: ${{ steps.version.outputs.version }}
          TAG: ${{ steps.tag.outputs.tag }}

      - name: Publish Release
        run: |
          echo "Updated Publishing release for version $VERSION_NAME..."
          # Add your publishing logic here
